// src/app/resources/beyond-good-intetions/article.ts
export type Article = {
    title: string;
    blurb: string;
    description?: string;
    paragraphs: string[];
  }
  
  export const article: Article = {
    title: 'Beyond Good Intentions',
    blurb: 'A savarna reflection on the limits of good intentions and the necessity of grace and courage in accountability.',
    description: 'In this reflection, I’m trying to sit with the gap between how I often see myself as a savarna person, and the reality of the harm my actions can cause others. I notice the many tempting ways my ego tries to protect me—by withdrawing, over-explaining, or defending my intentions. But what I’m slowly learning is that repair asks something different: to center the dignity of the person harmed, instead of guarding my own image to the self and others.',
    paragraphs: [
        'Mistakes can happen. My unlearning, my politics, my years of being able to name caste and call out injustice — these are not fragile glass vessels that, once cracked, cannot be mended. That paradox is the humbling place I am writing from: I want to keep my commitments to learning and solidarity, but I must first look at the harm I caused, without polishing it away with good intentions or theatrical remorse.',
        'I am writing as someone who believes themselves to be a “liberal savarna.” I have read, I have nodded in meetings, I have curated playlists of anti-caste readings for friends, I have taken pains to be the “different” savarna — the one who listens, who steps back, who champions marginalised voices. I have worn that identity like armor: it feels warm and self-affirming, because it reassures me that I am not like my own family—the caricature of the “abusive savarna” I fear becoming. I built elaborate reasons to convince myself that I was already different, already safe, already okay.',
        'Then, in a moment of action, I caused harm. I spoke in a way I should not have. I overstepped a boundary. I failed to notice a signal that someone was uncomfortable. A person was left hurt and diminished. Later, I saw how their body and presence shifted — withdrawing, shutting down, collapsing into silence — and I realized that my words, my actions, had landed on another person’s dignity like a weight they did not ask for.',
        'What followed in me was predictable and ugly and almost human. I felt shame, yes. But shame quickly ran into a different current: anger and resentment. I could hear a small, furious voice inside me saying: “Why are they picking on me? After everything I’ve done? After how much I’ve tried?” I resented being called out. I resented the possibility of being cancelled. I resented that, despite my carefully curated record of allyship — the labor I displayed as both merit badges and as markers of my very identity as a ‘different kind of savarna’ — a single mistake could seem to unravel it all. I even felt a thought that I know sounds cowardly: “I should never have put myself in a space like this; I should never have tried to show up.” That thought is the ego’s last-ditch defense: if I never show up, I can never cause harm. It is cowardice masquerading as safety.',
        'If you are reading and feel the twitch of recognition — that whisper that wants to defend, to explain, to make the incident a story of misunderstanding rather than harm — please stay with me. I will be painfully honest about what those defenses look like, why they are tempting, and why they are ultimately useless to the person harmed.',
        'First: the temptation to ghost. After an incident, the easiest escape route is withdrawal. Don’t reply to messages. Avoid the group chat. Pretend it never happened and let the wound crust over. Ghosting is attractive because it buys me time: time to let the social heat die down, time for the story to move on, time to avoid being present in the discomfort I caused. But ghosting is a second harm. It abandons the person who was harmed. It re-enacts the original betrayal by making them responsible for carrying the memory alone. If I cared about trust, I would know that absence is a cheap way to avoid repair.',
        'Second: over-anxious vulnerability. Another script I know well is to perform my own suffering. “I’m so ashamed, I’m devastated, this has ruined me.” It presses for comfort; it asks the harmed person to witness and soothe me. This is an old tactic: swap the roles, and you are suddenly the one deserving of care. It is appealing because it turns the crisis into a test of others’ empathy for me. But it again recenters me. It takes compassion that should be directed to the injured and redirects it toward my bruised ego.',
        'Third: narrative dilution. I have, in my toolkit, the ability to connect dots, to cite thinkers, to draft long essays that frame what happened inside broader histories and systemic patterns. I can spin context, reference theory, and write in ways that make my response look rigorous and self-aware. In a moment of crisis, I can say: “Well, this is complex — we were improvising; everyone is tired; power dynamics are messy.” I can even back this up with readings, articles, and academic citations, performing thoughtfulness while delaying the simple act of acknowledgment. These may all be true statements, but when deployed this way, they become cerebral gymnastics that blur the clarity of harm and diminish its specificity. The person harmed does not need my intellectual map of complexity at that moment. They need recognition of what happened to them — not another essay that makes culpability abstract and accountability distant.',
        'Fourth: virtue-signalling. I can remind people — subtly or overtly — of my unlearning journey: the books I’ve read, the protests I attended, the panels I spoke on. I can use those as proof of my intentions. That feels reassuring internally: “See? I’m not like others.” But reputation is not restoration. Presenting my credentials is an attempt to immunize myself against consequence, to convert accountability into a reputation exercise. It does not repair harm.',
        'Fifth, and perhaps the most dishonorable: resentment toward the person or community that calls me out. I have caught myself thinking, “Why are Dalit people picking on me? After all that I’ve done?” That sentence is poisonous in multiple ways. It externalizes responsibility; it paints critique as persecution; it frames callouts as a threat to my identity rather than a request for repair. Even naming this thought is uncomfortable. But naming it is necessary. This resentment is not an argument against accountability. It is a confession of how fragile my self-image is when it is threatened. It is the ego protecting its investments.',
        'So what is actually helpful? What, if I want to be accountable without performing virtue, must I do?',
        'First, center the harmed. The person who was harmed must set the terms. I should not force contact, apologies, or explanations. If they ask for no contact, my job is to respect that. If they ask for a mediated conversation, my job is to accept the forum they trust. Centering the harmed means prioritizing their safety, dignity, and agency above my need to be absolved.',
        'Second, listen without defending. If there is any conversation at all, my opening move should never be “I’m sorry you felt that way,” nor should it be “I didn’t mean to.” Those sentences either gaslight or beg for absolution. A more useful line is: “I hear you. I caused harm. I want to understand what you need.” If I feel compelled to explain, I should channel that energy into clarifying the factual sequence — only if asked — and otherwise defer to the harmed person’s account.',
        'Third, ask what repair looks like and follow their lead. Repair is not always monetary or performative. Sometimes it is silence, sometimes it is bearing witness, sometimes it is amplifying their voice, sometimes it is supporting their material needs. I must accept that repair might involve consequences: removal from facilitation roles, public accountability statements, wearing the discomfort of diminished standing. I must accept those consequences as necessary, not as unfair punishments.',
        'Fourth, build systems of accountability that bypass my goodwill. Put into place structures that do not depend on my continuously proven virtue. This means: a complaints channel that is confidential; pre-established safety marshals at events with explicit permission to intervene; staging practices that prioritize physical consent and bodily differences; rehearsal protocols that surface risky movements; named people who can be called to halt an action; an external mediator or restorative justice practitioner who can be engaged when harm occurs. These systems protect others even if I, personally, am not always trustworthy in the moment.',
        'Fifth, seek help — not to protect my reputation, but to increase my reliability. This might mean therapy or anti-bias coaching that is specifically accountable to the communities harmed. It might mean an accountability partner from outside my comfort zone — a person who can call me out and hold me to agreements. It might mean funding someone else’s work in the community as a gesture that takes responsibility without expecting gratitude.',
        'Sixth, do the internal work without weaponizing it. If I have to narrate my unlearning, let that narrative be private and functional. Let publicly shared reflections be short, centered on the harmed person, and on concrete steps being taken. Do not use the language of unlearning to dodge consequences. Do not demand forgiveness in public. Let the work be about changing behavior, not about restoring my public image.',
        'Seventh, be willing to step back. If I am part of organizing, recognize that sometimes accountability requires the immediate ceding of space. Stepping back is not a surrender — it is a practice of refusing to be the arbiter of my redemption. It also creates room for those harmed to breathe and to lead the process as they choose.',
        'Finally, accept the paradox: I cannot promise never to err. My personality, my spontaneity, my carelessness — these are not fully trustable on their own. If I am honest, I must say to others: “If you find me unreliable, tell me. If my language is risky, help me change it. If my presence is unsafe, I will step away.” Asking for help in this way is humbling, and it’s necessary. If my language cannot be trusted because it tends to rationalize, if my temperament tends to minimize, then I must ask for concrete supports: someone to review my facilitation plan, a named reviewer on all performances, rehearsal observers from diverse backgrounds, explicit consent scripts, and clear intervention phrases.',
        'To anyone like me — who wants to be liberal and also safe to be around — remember this: the only path that actually helps is courage plus grace. Courage to look squarely at the harm you caused (not at your intentions), and the grace to accept whatever repair the harmed person asks for, even when it is painful for you. Nothing else is a substitute. Ghosting, oversharing your vulnerability, diluting the narrative, virtue-signalling, or nursing resentment will only re-center you. They will not restore dignity. They will not rebuild trust.',
        'Mistakes can happen. That is not a license — it is a reality. What measures the sincerity of our unlearning is not how loudly we proclaim our commitments, but how we behave when those commitments are tested: whether we are willing to be diminished, to be corrected, to be absent from platforms we were used to occupying, and to invest in systems that make others safer. That is the hard work, and it is not glamorous. It does not offer immediate absolution or social applause. But it can lead to real repair.',
        'If you are reading this and you are someone I harmed: I am sorry. I do not ask you to forgive me. I ask you to tell me what you need, and I will follow your lead. If you do not wish to speak, I will respect that. I will work to ensure that others are safer. I will not recentre my pain over yours. I will not demand that my years of liberal performance protect me from consequence. I will submit my action to accountability that is not mine alone to police.',
        'And if you are reading this and you are, like me, a savarna who wants to be better: start with curiosity about the harm, not curiosity about yourself. Let curiosity be directed outward. Let your response be governed by the person harmed, not by your reputation. Create systems that do not depend on the best version of you showing up at all times. And when the ugly feelings — resentment, fear, anger — rise, name them out loud and then set them aside. They are part of the process, but they cannot be its center.',
        'Mistakes can happen. My politics and my unlearning are not irreparably broken by one error. But they are made real by how I respond: with the humility to be accountable, the courage to be diminished, and the grace to place repair above reputation. Nothing more, nothing less.',
        '***'
    ]
  }